name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: [self-hosted, nixos, bucees-tracker]
    steps:
      - uses: actions/checkout@v4

      - name: Run checks
        run: nix flake check